### PR TITLE
Update pornography-hosts

### PR DESCRIPTION
**Pull request by Yodatoo**
Taken from
https://toppornsites.co.uk/
http://thepornlist.com/
https://bestxxxsites.com/

### CODE REVIEW

**Comment by spirillen** [comment]
In reply to https://github.com/Sinfonietta/hostfiles/issues/98#issuecomment-605775101

I most admit I can't remember how you change the target of a pullrequest on Github :unamused: 

But close this PR. a do a new one, this time be sure you set the target right

**Comment by spirillen** [comment]
Step one

Make the changes to the file

image



Next step where you have to be careful

This is the right settings =>
image

At the end this should be what it looks like, except I created mine a a **draft** solely to @Sinfonietta attention to the fact this is only for demonstrative usage

image

Happy git'ting :smiley: :wave:

**Comment by Yodatoo** [comment]
So, you're saying I should just abandon/delete the old one, and redo?
I don't recall seeing "Create pull request". I see "Merge pull request".

**Comment by spirillen** [comment]
Yep. abandon the skip and resubmit these lines.... it's the fastest I can come up with..

**Comment by Yodatoo** [comment]
> 
> 
> Yep. abandon the ship and resubmit these lines.... it's the fastest I can come up with..

So, I've edited it again, and I see "Commit changes" button below. (There's no "Propose file changes" button.)

Perhaps I should add that if I click on that, I would see

> This branch has no conflicts with the base branch
> Merging can be performed automatically. 

and I see "Merge pull request". Would clicking on that do?

I was editing at "https://github.com/Yodatoo/hostfiles/edit/master/pornography-hosts"

**Comment by spirillen** [comment]
Try to merge it. It looks like you still are running in the same repo, and not a new fork from @Sinfonietta repo....

When you have done that, open a new merge request and see if you find anything similar to the dumps I posted earlier

**Comment by Yodatoo** [comment]
Actually, I tried to redo (though I didn't delete the old one first). Not sure what happened.

Anyway, so I clicked "Merge pull request" (but I forgot that I should click on the new one, not the old). So, now I got:

> Pull request successfully merged and closed
> You’re all set—the Yodatoo-patch-1 branch can be safely deleted.

Am I done?

**Comment by spirillen** [comment]
yes, with step 1

Now try to create a new Pull Request, https://github.com/Sinfonietta/hostfiles/compare/master...Yodatoo:master

and you'll see this image

image

Follow the guides... and you should be there. Then you'll have to work with @Sinfonietta about the next conflict that will appear, but don't worry, that one ain't hard to brake :smile: :wave:

**Comment by Yodatoo** [comment]
Thanks for your guidance. So, now I'm at

image

So, anything for me to do now?

**Comment by Yodatoo** [comment]
Do I also Delete branch. I see a msg saying it "can be safely deleted".

**Comment by spirillen** [comment]
You're done... but wait with the delete branch to it is merged (good karma) the next step is between you and @Sinfonietta :full_moon_with_face:

**Comment by Yodatoo** [comment]
OK. Thanks. So, it's relatively straight forward after all. :-)

**Comment by spirillen** [comment]
Yeah, when you know how to :smile: 

Next time, just remember to do the first merge request (pull request) straight against the source :+1: that would make it much easier :moon_cake:

**Comment by Yodatoo** [comment]
:ok_hand:

**Pull request merged**
